####1. Data set resetting

```{r}
library(dplyr)
bjclean<-read.csv("bjclean.csv",head=T)
str(bjclean)
bjclean$Value<-as.numeric(bjclean$Value)
bjclean<-bjclean %>% select(Year,Month, Day, Hour, Value, week,mean_Value_Day)
```

####2. Defining the a new variable: index, based on the AQI index on the US State Air Quality.

```{r}
index<-function(x){
  index<-numeric(length=length(x))
  for(i in 1:length(index)){
    if(x[i]<=50) 
      index[i]<-0
    else if((x[i]>=51) & (x[i]<=100)) 
      index[i]<-1
    else if((x[i]>=101) & (x[i]<=150))
      index[i]<-2
    else if((x[i]>=151) & (x[i]<=200)) 
      index[i]<-3
    else if((x[i]>=201) & (x[i]<=300))
      index[i]<-4
    else if((x[i]>=301) & (x[i]<=500)) 
      index[i]<-5
    else if(x[i]>=501) 
      index[i]<-6
  }
  index<-as.integer(index)
  return(index)
}
bjclean<-bjclean %>% 
  group_by(Month, Day) %>%
  mutate(max_Value_Day=max(Value)) %>%
  mutate(mean_index=index(mean_Value_Day)) %>%
  mutate(max_index=index(max_Value_Day)) %>%
  ungroup()
bjclean$mean_index<-as.factor(bjclean$mean_index)
bjclean$max_index<-as.factor(bjclean$max_index)
summary(bjclean)
levels(bjclean$mean_index)<-c(levels(bjclean$mean_index),"5","6")
levels(bjclean$max_index)<-c(levels(bjclean$max_index),"0")
summary(bjclean)
```
